### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by deepu105** [yeoman/yeoman-app#101]
Hi Guys,

Is the app supported in windows? I followed the getting started instructions application launches but there is nothing but a yeoman image there, build doesnt work as the platform check throws error.

If its not supported yet I would be willing to do some work to get it started

**Comment by stefanbuck** [comment]
Hi,

limited by my hardware I couldn't test it on Windows. In general it should work. First we should try to get `npm start` working. Afterwords we can figure out what's wrong with the build script.

Are you getting the "No installed generators found" message like in the screenshot below?

![screen shot 2016-02-02 at 12 34 56](https://cloud.githubusercontent.com/assets/1393946/12748250/6482164e-c9a9-11e5-9193-f098554394d3.png)


What is your console saying? It should be something like that:

```
App load time: 145ms
YO-Process { action: 'generator:init', args: [] }
APP { event: 'generator:installed-generators', data: [] }
```

**Comment by deepu105** [comment]
Nope no messages, there was only a console error coz of React.render
deprecation which i changed and the error was gone but still same
behaviour. Container launches and shows the yeoman image alone.

Few other things.

Npm start works it launches as said above
Npm build throws platform not supported error, i disabled the check to see
if there is any error thrown but nothing.
Npm test doesnt work either error says unable to identify the
script/test.js task
Tried to run the electron commands directly but same result.
There was no build folder at all
When i launch test from the launched app it throws some assertion error due
to unix like path checking for node modules folder

Btw one more thing im running node LTS and npm 3.7.0

Ill upgrade node to 5.x and give it a shot as well

**Comment by stefanbuck** [comment]
Yeah updating to node 5.x is definitely a good idea. As I sad before, let us get `npm start` working before we dive into the build issues. If you see the yeoman images the app boot was successful. So my guess is that something is wrong with the yo child process. To verify that the child process was initialize successfully, please add a log statement before and after ` this.yoProcess = fork(path.join(__dirname, 'yo', 'yo.js'));` in appwindows.js. Please also check if the `did-finish-load` event was triggered (same file, in the `show()` method.

**Comment by deepu105** [comment]
Ok ill check these today.

I think this could be a great app, coz I try to teach people to use yeoman
generators from cli( I'm from the core team of [Jhipster](jhipster.github.io))
many people are still scared of cli and they consider anything to do with
cli as complicated so for these kind of people an app like these would be a
good place to start with :)

**Comment by stefanbuck** [comment]
Many thanks for investigating this problem. Make yeoman available for a broader audience, is our goal and the reason why we started this project :wink:

**Comment by deepu105** [comment]
OK I have tried below

1. upgraded to node v5.5.0 & npm v3.7.1
running npm start gives just below, which is same as before nope upgrade

![image](https://cloud.githubusercontent.com/assets/1107223/12775870/52dad87a-ca8c-11e5-9109-ea5dc1871cc0.png)

2. I tried adding console.log in the appwindow.js it gave the same result as above so out of curiosity i added logs in app.js, main.js etc but I dont see any logs in the developer console

3. running the test within the launched window gives below
![image](https://cloud.githubusercontent.com/assets/1107223/12776110/49323db6-ca8e-11e5-9fe3-b4a3f7e5b294.png)

4. running npm test gives below
```

$ npm test

> yeoman-app@0.0.0 pretest D:\Projects\GIT\yeoman-app
> npm run lint


> yeoman-app@0.0.0 lint D:\Projects\GIT\yeoman-app
> eslint --ext=js --ext=jsx src spec


> yeoman-app@0.0.0 test D:\Projects\GIT\yeoman-app
> scripts/test.js

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
5. running npm run debug followed by npm run inspector gives below
```
$ npm run inspector

> yeoman-app@0.0.0 preinspector D:\Projects\GIT\yeoman-app
> open http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858

'open' is not recognized as an internal or external command,
operable program or batch file.
'port' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "inspector"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! yeoman-app@0.0.0 preinspector: `open http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yeoman-app@0.0.0 preinspector script 'open http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yeoman-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     open http://127.0.0.1:8080/?ws=127.0.0.1:8080&port=5858
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yeoman-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yeoman-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\GIT\yeoman-app\npm-debug.log

```

**Comment by stefanbuck** [comment]
Note that logs defined in a file under `src/browser/` are printed only to your terminal. Logs from `src/render/` are visible only in the dev tool console.

**Comment by deepu105** [comment]
There was no log on terminal as well

**Comment by stefanbuck** [comment]
I'm downloading a window 10 VM right now ... stay tuned

**Comment by stefanbuck** [comment]
I've run into some issues with the windows 10 image. But good news, on windows 7 the app is working. Will continue tomorrow my windows session.

**Comment by deepu105** [comment]
I can try on Linux but my goal is to get it working in Windows and provide any contribution possible from me

**Comment by stefanbuck** [comment]
Sure, we should definitely get it working on all common platforms. But I have no idea what cause the issue, right now.

**Comment by deepu105** [comment]
Im new to electron as well so trying to understand this, i don't see any
logs in terminal, is there anything to be done to enable that? I tried
putting logs everywhere but nothing shows up

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
Ok this is very weird, not sure if its an electron issue.

I always use git bash as my terminal in windows and was doing all this in it as well.

Just out of curiosity tried the same in a power-shell terminal and app works so not sure what is the problem.

If this wont be an issue when the actual packaged `.exe` is released then you can close this issue

**Comment by stefanbuck** [comment]
That's indeed strange. What about `npm run build`? Is it working and the build artifact executable?

**Comment by deepu105** [comment]
no build still doesnt work

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
here is trace from `npm run build`

```
PS D:\Projects\GIT\yeoman-app> npm run build

> yeoman-app@0.0.0 build D:\Projects\GIT\yeoman-app
> electron-compile --appDir . ./src/ ./static/ && node scripts/build.js

Path must be a string. Received undefined
Compilation failed!
For extra information, set the DEBUG environment variable to '*'

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Deepu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! yeoman-app@0.0.0 build: `electron-compile --appDir . ./src/ ./static/ && node scripts/build.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the yeoman-app@0.0.0 build script 'electron-compile --appDir . ./src/ ./static/ && node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yeoman-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-compile --appDir . ./src/ ./static/ && node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yeoman-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yeoman-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\GIT\yeoman-app\npm-debug.log
PS D:\Projects\GIT\yeoman-app>
```

running `electron-compile --appDir . ./src/ ./static/` 

```
electron-compile --appDir . ./src/ ./static/
Path must be a string. Received undefined
Compilation failed!
For extra information, set the DEBUG environment variable to '*'
PS D:\Projects\GIT\yeoman-app>
```

running `node scripts/build.js`

```
PS D:\Projects\GIT\yeoman-app> node scripts/build.js
[Error: Platform not supported yet!]
PS D:\Projects\GIT\yeoman-app>

```

**Comment by stefanbuck** [comment]
Opened a PR which should fix the build script https://github.com/yeoman/yeoman-app/pull/105

**Comment by deepu105** [comment]
Damn this has stopped working again :( I dont know whats wrong now

**Comment by deepu105** [comment]
doesnt work on latest master or my old branch which was working previously and my node env is still the same

**Comment by stefanbuck** [comment]
Let's try to clean up: remove the `.cache` folder and run `npm prune`.

**Comment by deepu105** [comment]
ok

Thanks & Regards,
Deepu
